project:
  type: book

book:
  title: "OOP for Scientific Computing Notes - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - part: 01/cmake/cmake.qmd
      chapters:
        - 01/cmake/01.qmd
        - 01/cmake/02.qmd
    - part: 01/fundamentals/00-fundamentals.qmd
      chapters: 
        - 01/fundamentals/01-vars.qmd
        - 01/fundamentals/02-types.qmd
        - 01/fundamentals/03-indirection.qmd
        - 01/fundamentals/04-control-flow.qmd
        - 01/fundamentals/05-oop.qmd

number-depth: 2

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



