project:
  type: book


book:
  title: "OOP for Scientific Computing Notes - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - reading.qmd
    - part: cmake/cmake.qmd
      chapters:
        - cmake/01.qmd
        - cmake/02.qmd
    - part: fundamentals/00-fundamentals.qmd
      chapters: 
        - fundamentals/01-vars.qmd
        - fundamentals/02-types.qmd
        - fundamentals/03-indirection.qmd
        - fundamentals/04-control-flow.qmd
        - fundamentals/05-oop.qmd
    - part: summary/overview.qmd
      chapters:
        - summary/oop.qmd
  downloads: pdf

number-depth: 2

highlight-style: pygments

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
