test_crtp_shape3: test_crtp_shape3.cc
	g++ -o test_crtp_shape3 test_crtp_shape3.cc
test_crtp3: test_crtp3.cc
	g++ -o test_crtp3 test_crtp3.cc
test_crtp_shape: test_crtp_shape.cc
	g++ -o test_crtp_shape test_crtp_shape.cc
test_enum: test_enum.cc
	g++ -o test_enum test_enum.cc
test_crtp: test_crtp.cc
	g++ -o test_crtp test_crtp.cc
test_independent_base: test_independent_base.cc
	g++ -o test_independent_base test_independent_base.cc
test_dependent_base: test_dependent_base.cc
	g++ -o test_dependent_base test_dependent_base.cc
test_partial_spec: test_partial_spec.cc
	g++ -o test_partial_spec test_partial_spec.cc
test_spec: test_spec.cc
	g++ -o test_spec test_spec.cc
varprint1: varprint1.cc
	g++ -o varprint1 varprint1.cc
test_stack: test_stack.cc stack1.hh
	g++ -o test_stack test_stack.cc
test_list2: test_list2.cc list.hh 
test_arr: arr_templ.cc
	g++ -o test_arr arr_templ.cc
test_fact: fact_templ.cc
	g++ -o test_fact fact_templ.cc 
test_list2: test_list2.cc list.hh
	g++ -o test_list2 test_list2.cc 

test_list: test_list.cc
	g++ -o test_list test_list.cc
test_templates: test_templates.cc basics.hh
	g++ -o test_templates test_templates.cc