
varprint1: varprint1.cc
	g++ -o varprint1 varprint1.cc
test_stack: test_stack.cc stack1.hh
	g++ -o test_stack test_stack.cc
test_list2: test_list2.cc list.hh 
test_arr: arr_templ.cc
	g++ -o test_arr arr_templ.cc
test_fact: fact_templ.cc
	g++ -o test_fact fact_templ.cc 
test_list2: test_list2.cc list.hh
	g++ -o test_list2 test_list2.cc 

test_list: test_list.cc
	g++ -o test_list test_list.cc
test_templates: test_templates.cc basics.hh
	g++ -o test_templates test_templates.cc