test_arr: arr_templ.cc
	g++ -o test_arr arr_templ.cc
test_fact: fact_templ.cc
	g++ -o test_fact fact_templ.cc 
test_list2: test_list2.cc list.hh
	g++ -o test_list2 test_list2.cc 

test_list: test_list.cc
	g++ -o test_list test_list.cc
test_templates: test_templates.cc basics.hh
	g++ -o test_templates test_templates.cc
