test_string: test_string.cc string.cc string.hh
	g++ -o test_string test_string.cc string.cc
test_time: test_time.cc time.cc time.hh
	g++ -o test_time test_time.cc time.cc
test_template: test_template.cc
	g++ -o test_template test_template.cc
test_gcd: test_gcd.cc
	g++ -o test_gcd test_gcd.cc
test_fraction: test_fraction.cc fraction.cc fraction.hh
	g++ -o test_fraction test_fraction.cc fraction.cc