test_string: string.h string.cc test_string.cc
	g++ -o test_string test_string.cc string.cc
test_time: time.h time.cc test_time.cc
	g++ -o test_time test_time.cc time.cc
motiv: motiv.cc
	g++ -o motiv motiv.cc