test_move: test_move.cc
	g++ -o test_move test_move.cc
motiv02: motiv02.cc
	g++ -o motiv02 motiv02.cc
test_string: string.h string.cc test_string.cc
	g++ -o test_string test_string.cc string.cc
test_time: time.h time.cc test_time.cc
	g++ -o test_time test_time.cc time.cc
motiv: motiv.cc
	g++ -o motiv motiv.cc