test_inheritence: inheritence.cc
	g++ -o test_inheritence inheritence.cc
test_cashregister: test_cashregister.cc cash_register.cc cash_register.hh
	g++ -o test_cashregister test_cashregister.cc cash_register.cc
menu: menu.cc
	g++ -o menu menu.cc
duff: duff.cc
	g++ -o duff duff.cc
test_car: test_car.cc car.cc car.hh
	g++ -o test_car test_car.cc car.cc
test_order: test_order.cc order.cc order.hh
	g++ -o test_order test_order.cc order.cc
test_vector: test_vector.cc
	g++ -o test_vector test_vector.cc
test_question: test_question.cc question.cc question.hh
	g++ -o test_question test_question.cc question.cc
test_account: test_account.cc account.cc account.hh
	g++ -o test_account test_account.cc account.cc
test_employee: test_employee.cc employee.cc employee.hh
	g++ -o test_employee test_employee.cc employee.cc