test_cashregister: test_cashregister.cc cash_register.cc cash_register.hh
	g++ -o test_cashregister test_cashregister.cc cash_register.cc
menu: menu.cc
	g++ -o menu menu.cc
duff: duff.cc
	g++ -o duff duff.cc
test_account: test_account.cc account.cc account.hh
	g++ -o test_account test_account.cc account.cc
