pointers: pointers.cc
	g++ pointers.cc -o pointers
references: references.cc
	g++ references.cc -o references
const: const.cc
	g++ const.cc -o const
if: if.cc
	g++ if.cc -o if
switch: switch.cc
	g++ switch.cc -o switch