account: account.cc
	g++ -o account account.cc
test_cashregister: test_cashregister.cc cash_register.cc cash_register.hh
	g++ -o test_cashregister test_cashregister.cc cash_register.cc
menu: menu.cc
	g++ -o menu menu.cc
duff: duff.cc
	g++ -o duff duff.cc
